feat: added dockerfile
olegnowikow/pr-1 pull request #13
Opened 2024-10-20 16:28 UTC by Stromkova

2024-10-20 17:47 UTC, olegnowikow requested changes

2024-10-20 17:47 UTC, olegnowikow commented on solve_quadratic.py
> +    discriminant = b**2 - 4*a*c
нет проверки `a` на ноль

2024-10-20 17:47 UTC, olegnowikow commented on solve_quadratic.py
> +import sys
для чего sys?

2024-10-20 19:07 UTC, Stromkova commented on solve_quadratic.py
> +    discriminant = b**2 - 4*a*c
Сделала

2024-10-21 20:50 UTC, olegnowikow commented on solve_quadratic.py
> +            print(f"Это не уравнение, так как a и b равны нулю.")
это все же уравнение :)

2024-10-21 20:50 UTC, olegnowikow approved these changes

2024-10-21 20:54 UTC, merged