feat: add Dockerfile.AD-158
olegnowikow/pr-1 pull request #15
Opened 2024-10-20 20:39 UTC by AD-158

2024-10-21 21:22 UTC, olegnowikow requested changes

2024-10-21 21:22 UTC, olegnowikow commented on AD-158/Docker/Readme.md
> +```docker build -t flask-hello-world .```
how to use Dockerfile.AD-158?

2024-10-22 14:31 UTC, AD-158 commented on AD-158/Docker/Readme.md
> +```docker build -t flask-hello-world .```
Флаг с указанием имени файла при постройке Image:  '-f <file_name>'
Исправил в Readme

2024-10-27 16:25 UTC, olegnowikow approved these changes

2024-10-27 16:25 UTC, merged